### ISSUE TITLE
Create forgotPassword.jsx

### ISSUE THREAD

**Issue by aviquez96** [Sustaingineeringubc/Horus-Monitoring#48] opened 2018-11-20 05:20 UTC
1) Make a text field that asks for the user's email    
2) Once asked, render 2 text fields, one asking for the email, and another for the key they got in     their email.    
3) If successful, redirect to "newPassword.jsx"

**Comment by jluisfgarza** [comment] 2018-11-20 07:47
Duplicate of #47

**Closed by jluisfgarza** 2018-11-20 07:47 UTC
